## https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
#- name: configure / Setup configure file
#  tmplate:
#    src: /etc/my.cnf.f/server.conf
#    owner: root
#    group: root
#    mode: 0644
#    backup: yes ##タイムスタンプ付きのバックアップファイルが作成される

- name: configure /Stop all Mariadb for initialization
  systemd:
    name: mariadb
    state: stopped

#- block:
- name: MariaDBの自動起動の有効化と起動
  systemd:
    name: mariadb
    state: started
    daemon_reload: yes
    enabled: yes

- name: configure / Change MariaDB root password
  mysql_user:
    login_user: "{{mariadb_root_user}}"
    login_password: "{{mariadb_root_pass}}"
    name: "{{mariadb_root_user}}"
    password: "{{mariadb_root_pass}}"
    state: present
    check_implicit_admin: yes



