- hosts: remote-server
  become: true

  tasks:
  - name: ホスト名の取得
    shell: hostname
    register: hostname

  - name: 日付の取得
    shell: date "+%Y%m%d"
    register: date
  
  - name: ディレクトリ作成
    file:
     path: /tmp/disk_log_{{ hostname.stdout }}_{{ date.stdout }}
     state: directory
     owner: ec2-user
     group: ec2-user
     mode: 775

  - name: 故障ディスクのディレクトリ名取得
    shell: df |grep {{ failed_disk_mountpoint }} | awk '{print $1}'
    ignore_errors: yes
    register: failed_disk_directoryl

  - name: S.M.A.R.T情報の収集
    shell: smartctl -a -x {{ failed_disk_directoryl.stdout }} > /tmp/disk_log_{{ hostname.stdout }}_{{ date.stdout }}/smartctllog
    #non-zero return codeが出るためignore_errorsをyesにした
    ignore_errors: yes

  - name: シリアル番号の取得
    shell: dmidecode -s system-serial-number
    register: serial_number

  - name: シリアル番号の出力
    debug: var=serial_number.stdout

  - name: ディレクトリのzip化 
    archive:
     path: /tmp/disk_log_{{ hostname.stdout }}_{{ date.stdout }}
     ##destがないとエラーが出る。
     dest: /tmp/disk_log_{{ hostname.stdout }}_{{ date.stdout }}.zip
     format: zip

  - name: ファイルコピー
    fetch:
      src: /tmp/disk_log_{{ hostname.stdout }}_{{ date.stdout }}.zip
      dest: /Users/mistasunagahiroka/ansible_test/
      #dest以下にzipファイルをコピーするためflatはyes
      flat: yes