- name: Depoy Database for WordPress
  hosts: databases
  become: true
  roles:
    - { role: common, tags: common} #OSの基本設定
    - { role: mairadb, tags: mariadb} #DBの構築

- name: Depoy Application for WordPress
  hosts: apps
  become: true
  roles:
    - {role: common, tags: common} #OSの基本設定
    - {role: nginx, tags: nginx} #nginxの構築
    - {role: php-fpm, tags: php-fpm} #PHPの実行環境の構築
    - {role: wordpress, tags: wordpress} #WordPressの展開
  